### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by chengchengowen** [tensorpack/zmq_ops#3]
I am trying to compile zmq_ops and got following errors. Does anyone know how to solve it?
Many thanks!

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-G1DpYQ-build/setup.py", line 5, in <module>
        from zmq_ops.common import maybe_compile, get_ext_suffix
      File "zmq_ops/__init__.py", line 4, in <module>
        from .zmq_ops import *
      File "zmq_ops/zmq_ops.py", line 27, in <module>
        _zmq_ops = _load_op()
      File "zmq_ops/zmq_ops.py", line 21, in _load_op
        maybe_compile()
      File "zmq_ops/common.py", line 50, in maybe_compile
        ret = compile()
      File "zmq_ops/common.py", line 34, in compile
        py_ldflags = sysconfig.get_config_var('LDFLAGS') + ' -lpython' + sysconfig.get_config_var('LDVERSION')
    TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by ppwwyyxx** [comment]
What's your python version?

**Comment by chengchengowen** [comment]
My version is 2.7, only use sysconfig.get_config_var('VERSION') is ok. The  "sysconfig.get_config_var('LDVERSION') or sysconfig.get_config_var('VERSION')" is still not working.

**Comment by ppwwyyxx** [comment]
sorry. should work now.
