### ISSUE TITLE
python install fail

### ISSUE THREAD

**Issue by SeaOfOcean** [tensorpack/zmq_ops#4]
Hi, I try to pip install zmq_ops-master but got error, not sure how to deal with it

```
Processing /data1/sampsonsong/zmq_ops-master
    Complete output from command python setup.py egg_info:
    make: Entering directory `/tmp/pip-req-build-GxGDpE/src'
    [cc] zmq_pull_op.cc ...
    In file included from zmq_pull_op.cc:13:0:
    zmq_conn.h: In constructor ¡®tensorpack::ZMQConnection::ZMQConnection(const tensorpack::ZMQSocketDef&)¡¯:
    zmq_conn.h:59:52: error: could not convert ¡®def¡¯ from ¡®const tensorpack::ZMQSocketDef¡¯ to ¡®std::string {aka std::basic_string<char>}¡¯
         def_{def}, ctx_{1}, sock_{ctx_, def.socket_type} {
                                                        ^
    zmq_conn.h:59:52: warning: missing initializer for member ¡®tensorpack::ZMQSocketDef::socket_type¡¯ [-Wmissing-field-initializers]
    zmq_conn.h:59:52: warning: missing initializer for member ¡®tensorpack::ZMQSocketDef::hwm¡¯ [-Wmissing-field-initializers]
    zmq_conn.h:59:52: warning: missing initializer for member ¡®tensorpack::ZMQSocketDef::bind¡¯ [-Wmissing-field-initializers]
    make: *** [obj/zmq_pull_op.o] Error 1
    make: Leaving directory `/tmp/pip-req-build-GxGDpE/src'
    Compile ops by command TF_CXXFLAGS="-I/usr/lib/python2.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0" TF_LDFLAGS="-L/usr/lib/python2.7/site-packages/tensorflow -ltensorflow_framework" EXT_SUFFIX=".so" PYTHON_CXXFLAGS="-isystem /usr/include/python2.7" PYTHON_LDFLAGS="-Wl,-z,relro -lpython2.7" make -C "/tmp/pip-req-build-GxGDpE/zmq_ops/../src" ...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-GxGDpE/setup.py", line 5, in <module>
        from zmq_ops.common import maybe_compile, get_ext_suffix
      File "zmq_ops/__init__.py", line 4, in <module>
        from .zmq_ops import *
      File "zmq_ops/zmq_ops.py", line 27, in <module>
        _zmq_ops = _load_op()
      File "zmq_ops/zmq_ops.py", line 21, in _load_op
        maybe_compile()
      File "zmq_ops/common.py", line 53, in maybe_compile
        raise RuntimeError("ops compilation failed!")
    RuntimeError: ops compilation failed!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-GxGDpE/

```

**Comment by ppwwyyxx** [comment]
Cannot reproduce. Looks like either you've modified the code, or your compiler might have some issues.

**Comment by SeaOfOcean** [comment]
Thanks for your reply @ppwwyyxx 
I did not modify the code.
For your instruction

```
Install tensorflow, libzmq, as well as the zmq.hpp header from cppzmq.
```

can you provide the version of tensorflow, libzmq (as well as how you install libzmp)?
In addition, how to deal with "zmq.hpp header from cppzmq"?

**Comment by ppwwyyxx** [comment]
zmq.hpp should be somewhere your compiler will look for, such as under `src/` or `/usr/include` or `$CPATH`.

I think it's an issue with your compiler. Seems like it does not understand the initialization syntax `def_{def}`. You can split the line into multiple lines to confirm this. Are you using gcc4?

I use gcc6 but I assume gcc5 would also work.

**Comment by SeaOfOcean** [comment]
upgrade to gcc6 solved my issue, thanks so much!!!

**Comment by ald2004** [comment]
gcc version 4.8.5
zmq_conn.h
#68 def_{def.end_point}, ctx_{1}, sock_{ctx_, def.socket_type} {

**Comment by ald2004** [comment]
gcc version 4.8.5
zmq_conn.h
#68 def_(def), ctx_{1}, sock_{ctx_, def.socket_type} {

gooooooogle a lot got nothing.
i think (  is copy def to def_ , but { copy equals copy str(def) to def_.
compiled pass. i will test.

**Comment by ppwwyyxx** [comment]
As https://github.com/tensorpack/zmq_ops says gcc 4.8.5 is not supported
